export class UltimosResultados {
    constructor(
        public logosimulador?: string,
        public idCalendario?: number,
        public Fecha?: string,
        public Fecha_No?: string,
        public idDivision?: number,
        public NombreDivision?: string,
        public nombreEvento?: string,
        public Posicion?: string,
        public nuevoELO?: any,
        public nuevoSR?: any,
        public linkOficial?: string,
        public idPiloto?: number,
        public idTorneo?: number,
        public ImgTrack?: string,
        public nombrePista?: string,
        public Mapa?: any,
        public Bandera?: string,
        public idEstadoCarrera?: number,
        public EstadoCarrera?: string,
        public nombreEventoCorto?: string,
        public logotorneo?: any,
        public permiteReportes?: number,
        public requiereRepeticion?: number,
        public plazoEnvioRepeticion?: any,
        public horasInicioReportes?: any,
        public horasFinReportes?: any,
        public idCategoria?: number,
        public nombrecatcoche?: string,
        public logomarcacoche?: string,
        public catPiloto?: string,
        public tipoPiloto?: string,
        public imgBanner?: any,
        public urlBanner?: any,
        public nombreTorneo?: any,
    ){}
}